master_db:
  db_host: "pgsql"
  db_port: 5432
  db_user: "postgres"
  db_password: "{{PGSQL_PASSWORD}}"
  db_name: "pumpelf"

server:
  host: 0.0.0.0
  port: 8080

rpcs:
  - rpc_url: '{{RPC_URL}}'
    chain_id: 11155111 # 测试网
    start_block: 7345203
    event_start_block: 7345203
    header_buffer_size: 200 # 区块缓冲大小
    contracts:
      - "0x99d2f8e0d9267c22fbecedbc505f2c2f1bba3517"

contract_infos:
  - chain_id: 11155111
    token_base_address: "0x99d2f8e0d9267c22fbecedbc505f2c2f1bba3517"