---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: apollo
  name: apollo
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/name: apollo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s.kuboard.cn/name: apollo
    spec:
      containers:
        - command:
            - per_apollo
            - api
          image: 'registry.ap-northeast-1.aliyuncs.com/omni-new/per_apollo:{{IMAGE_VERSION}}'
          imagePullPolicy: IfNotPresent
          name: apollo-api
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - command:
            - per_apollo
            - sync
          image: 'registry.ap-northeast-1.aliyuncs.com/omni-new/per_apollo:{{IMAGE_VERSION}}'
          imagePullPolicy: IfNotPresent
          name: apollo-sync
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: alihub
      initContainers:
        - command:
            - per_apollo
            - migrate
          image: 'registry.ap-northeast-1.aliyuncs.com/omni-new/per_apollo:{{IMAGE_VERSION}}'
          imagePullPolicy: IfNotPresent
          name: migrate
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: apollo
  name: apollo
  namespace: default
spec:
  clusterIP: 10.43.16.106
  clusterIPs:
    - 10.43.16.106
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  publishNotReadyAddresses: true
  selector:
    k8s.kuboard.cn/name: apollo
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: apollo
  name: apollo
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: api.pumpelf.ai
      http:
        paths:
          - backend:
              service:
                name: apollo
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - api.pumpelf.ai
      secretName: pumpelf.ai

