---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: nekoswap-runes
  name: nekoswap-runes
  namespace: default
  resourceVersion: '615941'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/name: nekoswap-runes
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s.kuboard.cn/name: nekoswap-runes
    spec:
      containers:
        - command:
            - per_apollo
            - api
          image: 'registry.eu-central-1.aliyuncs.com/nekoswap/runes:{{IMAGE_VERSION}}'
          imagePullPolicy: IfNotPresent
          name: api
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - command:
            - per_apollo
            - sync
          image: 'registry.eu-central-1.aliyuncs.com/nekoswap/runes:{{IMAGE_VERSION}}'
          imagePullPolicy: IfNotPresent
          name: sync
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: ali-deguo-hub
      initContainers:
        - command:
            - per_apollo
            - migrate
          image: 'registry.eu-central-1.aliyuncs.com/nekoswap/runes:{{IMAGE_VERSION}}'
          imagePullPolicy: IfNotPresent
          name: migrate
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: nekoswap-runes
  name: nekoswap-runes
  namespace: default
  resourceVersion: '615789'
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  publishNotReadyAddresses: true
  selector:
    k8s.kuboard.cn/name: nekoswap-runes
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/name: nekoswap-runes
  name: nekoswap-runes
  namespace: default
  resourceVersion: '615810'
spec:
  ingressClassName: nginx
  rules:
    - host: testapi.nekoswap.finance
      http:
        paths:
          - backend:
              service:
                name: nekoswap-runes
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - testapi.nekoswap.finance
      secretName: nekoswap.finance

