name: per_apollo Image Build And Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.get-commit-sha.outputs.sha }}
      ecr_registry: ${{ steps.login-ecr.outputs.registry }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get short SHA
        id: get-commit-sha
        run: echo "::set-output name=sha::$(git rev-parse --short=7 HEAD)"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ALIL_USERNAME }}
          password: ${{ secrets.DOCKER_ALIL_PASSWORD }}
          registry: "registry.ap-northeast-1.aliyuncs.com"

      - name: Build and push Docker image
        env:
          COMMIT_SHA: ${{ steps.get-commit-sha.outputs.sha }}

        run: |
          IMAGE_URL="registry.ap-northeast-1.aliyuncs.com/omni-new/per_apollo:${COMMIT_SHA}"
          echo $IMAGE_URL
          sed -i 's|{{PGSQL_PASSWORD}}|'"${{ secrets.PGSQL_PASSWORD }}"'|g' config-demo.yaml
          sed -i 's|{{RPC_URL}}|'"${{ secrets.RPC_URL }}"'|g' config-demo.yaml
          docker build -t ${IMAGE_URL} .
          docker push ${IMAGE_URL}
      - name: Update Deploy Version
        run: |
          sed -i 's/{{IMAGE_VERSION}}/${COMMIT_SHA}/g' mainfest.yaml

      - name: Deploy to k3s
        uses: steebchen/kubectl@master
        with:
          config: ${{ secrets.DOCKER_KUBE }}
          command: apply -f mainfest.yaml
